cmake_minimum_required(VERSION 3.14)

find_package(Boost MODULE REQUIRED filesystem)

add_library(interface__commands
    interface/CommandsInterface.cpp
    interface/CommandsInterface.h
    commands/BaseUserCommand.h
    commands/BaseUserCommand.cpp
    commands/ErrorUserCommand.h
    commands/trust_line_channels/InitChannelCommand.h
    commands/trust_line_channels/InitChannelCommand.cpp
    commands/trust_line_channels/ContractorListCommand.h
    commands/trust_line_channels/ContractorListCommand.cpp
    commands/trust_line_channels/GetChannelInfoCommand.h
    commands/trust_line_channels/GetChannelInfoCommand.cpp
    commands/trust_line_channels/GetChannelInfoByAddressesCommand.h
    commands/trust_line_channels/GetChannelInfoByAddressesCommand.cpp
    commands/trust_line_channels/SetChannelContractorAddressesCommand.h
    commands/trust_line_channels/SetChannelContractorAddressesCommand.cpp
    commands/trust_line_channels/SetChannelContractorCryptoKeyCommand.h
    commands/trust_line_channels/SetChannelContractorCryptoKeyCommand.cpp
    commands/trust_line_channels/RegenerateChannelCryptoKeyCommand.h
    commands/trust_line_channels/RegenerateChannelCryptoKeyCommand.cpp
    commands/trust_line_channels/RemoveChannelCommand.h
    commands/trust_line_channels/RemoveChannelCommand.cpp
    commands/trust_lines/InitTrustLineCommand.h
    commands/trust_lines/InitTrustLineCommand.cpp
    commands/trust_lines/SetOutgoingTrustLineCommand.h
    commands/trust_lines/SetOutgoingTrustLineCommand.cpp
    commands/trust_lines/CloseIncomingTrustLineCommand.h
    commands/trust_lines/CloseIncomingTrustLineCommand.cpp
    commands/trust_lines/ShareKeysCommand.h
    commands/trust_lines/ShareKeysCommand.cpp
    commands/trust_lines/RemoveTrustLineCommand.h
    commands/trust_lines/RemoveTrustLineCommand.cpp
    commands/trust_lines/ResetTrustLineCommand.h
    commands/trust_lines/ResetTrustLineCommand.cpp
    commands/payments/CreditUsageCommand.cpp
    commands/payments/CreditUsageCommand.h
    commands/payments/CreditUsageExchangeCommand.cpp
    commands/payments/CreditUsageExchangeCommand.h
    commands/max_flow_calculation/InitiateMaxFlowCalculationCommand.h
    commands/max_flow_calculation/InitiateMaxFlowCalculationCommand.cpp
    commands/max_flow_calculation/InitiateMaxFlowExchangeCalculationCommand.h
    commands/max_flow_calculation/InitiateMaxFlowExchangeCalculationCommand.cpp
    commands/max_flow_calculation/EstimateReceiveForPaymentAmountCommand.h
    commands/max_flow_calculation/EstimateReceiveForPaymentAmountCommand.cpp
    commands/max_flow_calculation/EstimatePaymentForReceiveAmountCommand.h
    commands/max_flow_calculation/EstimatePaymentForReceiveAmountCommand.cpp
    commands/max_flow_calculation/InitiateMaxFlowCalculationFullyCommand.h
    commands/max_flow_calculation/InitiateMaxFlowCalculationFullyCommand.cpp
    commands/total_balances/TotalBalancesCommand.h
    commands/total_balances/TotalBalancesCommand.cpp
    commands/history/HistoryPaymentsCommand.h
    commands/history/HistoryPaymentsCommand.cpp
    commands/history/HistoryPaymentsAllEquivalentsCommand.h
    commands/history/HistoryPaymentsAllEquivalentsCommand.cpp
    commands/history/HistoryTrustLinesCommand.h
    commands/history/HistoryTrustLinesCommand.cpp
    commands/history/HistoryWithContractorCommand.h
    commands/history/HistoryWithContractorCommand.cpp
    commands/history/HistoryAdditionalPaymentsCommand.h
    commands/history/HistoryAdditionalPaymentsCommand.cpp
    commands/trust_lines_list/GetFirstLevelContractorsCommand.h
    commands/trust_lines_list/GetFirstLevelContractorsCommand.cpp
    commands/trust_lines_list/GetTrustLinesCommand.h
    commands/trust_lines_list/GetTrustLinesCommand.cpp
    commands/trust_lines_list/GetTrustLineByAddressCommand.h
    commands/trust_lines_list/GetTrustLineByAddressCommand.cpp
    commands/trust_lines_list/GetTrustLineByIDCommand.h
    commands/trust_lines_list/GetTrustLineByIDCommand.cpp
    commands/trust_lines_list/EquivalentListCommand.h
    commands/trust_lines_list/EquivalentListCommand.cpp
	commands/trust_lines_list/GetAllTrustLineCommand.h
	commands/trust_lines_list/GetAllTrustLineCommand.cpp
    commands/subsystems_controller/SubsystemsInfluenceCommand.h
    commands/subsystems_controller/SubsystemsInfluenceCommand.cpp
    commands/subsystems_controller/TrustLinesInfluenceCommand.h
    commands/subsystems_controller/TrustLinesInfluenceCommand.cpp
    commands/transactions/PaymentTransactionByCommandUUIDCommand.h
    commands/transactions/PaymentTransactionByCommandUUIDCommand.cpp
    commands/general/RemoveOutdatedCryptoDataCommand.h
    commands/general/RemoveOutdatedCryptoDataCommand.cpp
    commands/rates/SetExchangeRateCommand.h
    commands/rates/SetExchangeRateCommand.cpp
    commands/rates/GetExchangeRateCommand.h
    commands/rates/GetExchangeRateCommand.cpp
    commands/rates/ListExchangeRatesCommand.h
    commands/rates/ListExchangeRatesCommand.cpp
    commands/rates/RemoveExchangeRateCommand.h
    commands/rates/RemoveExchangeRateCommand.cpp
    commands/rates/ClearExchangeRatesCommand.h
    commands/rates/ClearExchangeRatesCommand.cpp)

target_include_directories(interface__commands
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}
        ${CMAKE_SOURCE_DIR}/src/core/interface
)

target_compile_features(interface__commands
    PRIVATE
        cxx_std_20
)

target_link_libraries(interface__commands
    PUBLIC
        Boost::system
        Boost::filesystem
        common)
